[package]
name = "mnist-neural-net"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
indicatif = "0.17.8"
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
